"""initial setup

Revision ID: 9b22eb2cb4d2
Revises: 
Create Date: 2022-10-21 21:10:17.653620

"""
from alembic import op
import sqlalchemy as sa

from app.models import GUID

# revision identifiers, used by Alembic.
revision = '9b22eb2cb4d2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
        sa.Column('id', GUID(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('password', sa.String(), nullable=False),
        sa.Column('photo', sa.String(), nullable=True),
        sa.Column('gender', sa.Enum('Male', 'Female', 'Other', name='genderchoices'), server_default='Other', nullable=True),
        sa.Column('verified', sa.Boolean(), server_default='False', nullable=False),
        sa.Column('role', sa.Enum('User', 'IBD', 'OEM', name='rolechoices'), server_default='User', nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
