"""add captcha table

Revision ID: b73c8d4fe51a
Revises: dd2896db11e4
Create Date: 2022-10-28 08:32:16.903045

"""
from alembic import op
import sqlalchemy as sa

from app.models import GUID

# revision identifiers, used by Alembic.
revision = 'b73c8d4fe51a'
down_revision = 'dd2896db11e4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('captcha',
        sa.Column('id', GUID(), nullable=False),
        sa.Column('code', sa.String(), nullable=False),
        sa.Column('token', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('captcha')
    # ### end Alembic commands ###
