"""add videos

Revision ID: dd2896db11e4
Revises: 9b22eb2cb4d2
Create Date: 2022-10-24 13:55:45.800191

"""
from alembic import op
import sqlalchemy as sa

from app.models import GUID

# revision identifiers, used by Alembic.
revision = 'dd2896db11e4'
down_revision = '9b22eb2cb4d2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos',
        sa.Column('id', GUID(), nullable=False),
        sa.Column('video_id', sa.String(), nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('duration', sa.Integer(), nullable=False),
        sa.Column('platform', sa.Enum('Dailymotion', 'VK', 'Youtube', name='platformchoices'), server_default='Dailymotion', nullable=True),
        sa.Column('action', sa.Enum('Ignore', 'Download', 'Pending', name='actionchoices'), server_default='Pending', nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('video_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('videos')
    # ### end Alembic commands ###
