"""added gender to users table

Revision ID: e87d38a5f423
Revises: 004352ce0001
Create Date: 2022-10-21 16:01:59.495219

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e87d38a5f423'
down_revision = '004352ce0001'
branch_labels = None
depends_on = None

gender_choices = sa.Enum(
    'Male', 'Female', 'Other',
    name='gender_choices'
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    gender_choices.create(op.get_bind())
    op.add_column('users', sa.Column('gender', sa.Enum('male', 'female', 'other', name='gender_choices'), default='Other'))
    op.execute('ALTER TABLE users ALTER COLUMN gender TYPE gender_choices USING gender::gender_choices;')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('gender', server_default='Other', nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('users', 'gender')
    # ### end Alembic commands ###
